version: '3.4'

services:
  mongopythonb:
    image: mongopythonb
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn mongo:app --host 0.0.0.0 --port 27018"]
    ports:
      - 27018:27018
      - 27017:27017
      - 5678:5678
